export const FALLBACK_CATEGORIES = [
  { id: 101, nameBn: "রুদ্রাক্ষ", slug: "rudraksha", image: "/images/p-mala.jpg", description: "নেপালি ও ভারতীয় অরিজিনাল রুদ্রাক্ষ — বিভিন্ন মুখী ও আকারে।", sortOrder: 1, isActive: true },
  { id: 102, nameBn: "পূজা সামগ্রী", slug: "puja-samagri", image: "/images/p-puja-thali.jpg", description: "পূজার প্রয়োজনীয় সব সামগ্রী এক জায়গায়।", sortOrder: 2, isActive: true },
  { id: 103, nameBn: "পিতলের ব্রেসলেট", slug: "brass-bracelet", image: "/images/p-bracelet.jpg", description: "হাতে তৈরি পিতলের ঐতিহ্যবাহী ব্রেসলেট।", sortOrder: 3, isActive: true },
  { id: 104, nameBn: "পিতলের সামগ্রী", slug: "brass-samagri", image: "/images/p-kalash.jpg", description: "পিতলের কলস, প্রতিমা, ঘণ্টা ও পূজার সামগ্রী।", sortOrder: 4, isActive: true },
  { id: 105, nameBn: "রুদ্রাক্ষের ব্রেসলেট", slug: "rudraksha-bracelet", image: "/images/p-bracelet.jpg", description: "রুদ্রাক্ষের দানা দিয়ে তৈরি ব্রেসলেট ও হ্যান্ড চেইন।", sortOrder: 5, isActive: true },
  { id: 106, nameBn: "রুদ্রাক্ষের মালা", slug: "rudraksha-mala", image: "/images/p-mala.jpg", description: "১০৮+১ দানার জপমালা, রুদ্রাক্ষের মালা।", sortOrder: 6, isActive: true },
  { id: 107, nameBn: "অন্যান্য", slug: "others", image: "/images/p-lingam.jpg", description: "স্ফটিক, শিবলিংগ, তান্ত্রিক ও অন্যান্য সামগ্রী।", sortOrder: 7, isActive: true },
];

export const FALLBACK_PRODUCTS = [
  { id: 201, code: "SR-1001", nameBn: "৫ মুখী রুদ্রাক্ষের মালা (১০৮+১) – নেপালি", slug: "5-mukhi-rudraksha-mala-nepali", categoryId: 106, price: 1700, oldPrice: 2000, image: "/images/p-mala.jpg", images: ["/images/p-mala.jpg"], shortDesc: "নেপালি অরিজিনাল ৫ মুখী রুদ্রাক্ষ, ১০৮+১ দানা", description: "নেপাল থেকে সরাসরি সংগৃহীত ৫ মুখী রুদ্রাক্ষের জপমালা। প্রতিটি দানা হাতে বাছাই করা।", stock: 25, soldCount: 148, isLive: true, isOffer: true, offerLabel: "১৫% ছাড়", sortOrder: 1, createdAt: new Date("2026-10-01T10:00:00Z") },
  { id: 202, code: "SR-1002", nameBn: "পিতলের কূর্ম দেব", slug: "brass-kurma-tortoise", categoryId: 104, price: 380, oldPrice: 450, image: "/images/p-brass-turtle.jpg", images: ["/images/p-brass-turtle.jpg"], shortDesc: "হাতে খোদাই করা পিতলের কূর্ম প্রতিমা", description: "ঘর ও পূজার ঘরে রাখার জন্য আকর্ষণীয় পিতলের কূর্ম দেব।", stock: 40, soldCount: 96, isLive: true, isOffer: false, offerLabel: null, sortOrder: 2, createdAt: new Date("2026-10-01T11:00:00Z") },
  { id: 203, code: "SR-1003", nameBn: "২-৫ মুখী রুদ্রাক্ষ মালা", slug: "2-5-mukhi-rudraksha-mala", categoryId: 106, price: 3500, oldPrice: null, image: "/images/p-mala.jpg", images: ["/images/p-mala.jpg"], shortDesc: "বিশেষ সংযোজনের ২ থেকে ৫ মুখী রুদ্রাক্ষ মালা", description: "নির্বাচিত ২, ৩, ৪ ও ৫ মুখী রুদ্রাক্ষ দিয়ে গাঁথানো বিশেষ মালা।", stock: 12, soldCount: 41, isLive: true, isOffer: false, offerLabel: null, sortOrder: 3, createdAt: new Date("2026-10-01T12:00:00Z") },
  { id: 204, code: "SR-1004", nameBn: "৩৩ সিং রুদ্রাক্ষের ব্রেসলেট মালা", slug: "33-sing-rudraksha-bracelet", categoryId: 105, price: 2300, oldPrice: 2800, image: "/images/p-bracelet.jpg", images: ["/images/p-bracelet.jpg"], shortDesc: "৩৩ সিং রুদ্রাক্ষ দিয়ে তৈরি ব্রেসলেট", description: "৩৩ সিং রুদ্রাক্ষের দানা দিয়ে তৈরি আলাদাভাবে পরিধানযোগ্য ব্রেসলেট।", stock: 18, soldCount: 77, isLive: true, isOffer: true, offerLabel: "বিশেষ মূল্য", sortOrder: 4, createdAt: new Date("2026-10-01T13:00:00Z") },
  { id: 205, code: "SR-1005", nameBn: "৫-৬-৭ মুখী রুদ্রাক্ষ মালা", slug: "5-6-7-mukhi-mala", categoryId: 106, price: 2300, oldPrice: null, image: "/images/p-mala.jpg", images: ["/images/p-mala.jpg"], shortDesc: "৫, ৬ ও ৭ মুখী রুদ্রাক্ষের সমন্বয়ে মালা", description: "বিশেষ ভাবে বাছাই করা ৫, ৬ ও ৭ মুখী রুদ্রাক্ষের সমন্বয়ে তৈরি মালা।", stock: 15, soldCount: 33, isLive: true, isOffer: false, offerLabel: null, sortOrder: 5, createdAt: new Date("2026-10-01T14:00:00Z") },
  { id: 206, code: "SR-1006", nameBn: "স্ফটিকের মালা", slug: "sphatik-mala", categoryId: 107, price: 1200, oldPrice: 1500, image: "/images/p-lingam.jpg", images: ["/images/p-lingam.jpg"], shortDesc: "প্রাকৃতিক স্ফটিক দানার মালা", description: "প্রাকৃতিক স্ফটিক (স্ফটিক) দানা দিয়ে তৈরি মালা।", stock: 22, soldCount: 64, isLive: true, isOffer: true, offerLabel: "২০% ছাড়", sortOrder: 6, createdAt: new Date("2026-10-01T15:00:00Z") },
  { id: 207, code: "SR-1007", nameBn: "পিতলের পূজা থালি সেট", slug: "brass-puja-thali-set", categoryId: 102, price: 1250, oldPrice: 1600, image: "/images/p-puja-thali.jpg", images: ["/images/p-puja-thali.jpg"], shortDesc: "সম্পূর্ণ পিতলের পূজা থালি সেট", description: "খোদাই করা পিতলের থালি, ছোট পাত্র, ঘণ্টা, দীপ ও ধূপদানী সহ পূজা সেট।", stock: 10, soldCount: 52, isLive: true, isOffer: true, offerLabel: "২২% ছাড়", sortOrder: 7, createdAt: new Date("2026-10-01T16:00:00Z") },
  { id: 208, code: "SR-1008", nameBn: "পিতলের কলস জোড়া", slug: "brass-kalash-pair", categoryId: 104, price: 950, oldPrice: null, image: "/images/p-kalash.jpg", images: ["/images/p-kalash.jpg"], shortDesc: "ঠাটানো পিতলের কলস (২টি)", description: "ঐতিহ্যবাহী নকশায় তৈরি পিতলের কলস জোড়া।", stock: 28, soldCount: 45, isLive: true, isOffer: false, offerLabel: null, sortOrder: 8, createdAt: new Date("2026-10-01T17:00:00Z") },
  { id: 209, code: "SR-1009", nameBn: "কালো পাথরের শিবলিংগ", slug: "black-stone-shivling", categoryId: 107, price: 1450, oldPrice: 1800, image: "/images/p-lingam.jpg", images: ["/images/p-lingam.jpg"], shortDesc: "পালিশড কালো পাথরের শিবলিংগ ও আসন", description: "একটি টুকরো কালো পাথর থেকে নির্মিত পালিশড শিবলিংগ।", stock: 9, soldCount: 38, isLive: true, isOffer: true, offerLabel: "১৯% ছাড়", sortOrder: 9, createdAt: new Date("2026-10-01T18:00:00Z") },
  { id: 210, code: "SR-1010", nameBn: "রুদ্রাক্ষের ব্রেসলেট (ক্লাসিক)", slug: "rudraksha-bracelet-classic", categoryId: 105, price: 650, oldPrice: 850, image: "/images/p-bracelet.jpg", images: ["/images/p-bracelet.jpg"], shortDesc: "দৈনিক পরিধানের রুদ্রাক্ষ ব্রেসলেট", description: "প্রাকৃতিক রুদ্রাক্ষের দানা ও পিতলের স্পেসার দিয়ে তৈরি ক্লাসিক ব্রেসলেট।", stock: 60, soldCount: 210, isLive: true, isOffer: true, offerLabel: "২৩% ছাড়", sortOrder: 10, createdAt: new Date("2026-10-01T19:00:00Z") },
  { id: 211, code: "SR-1011", nameBn: "পিতলের ঘণ্টা ও দীপ সেট", slug: "brass-bell-diya-set", categoryId: 102, price: 780, oldPrice: null, image: "/images/p-puja-thali.jpg", images: ["/images/p-puja-thali.jpg"], shortDesc: "পূজার ঘণ্টা ও পিতলের দীপ", description: "মোটা পিতলের তৈরি পূজার ঘণ্টা ও দীপের সেট।", stock: 35, soldCount: 71, isLive: true, isOffer: false, offerLabel: null, sortOrder: 11, createdAt: new Date("2026-10-01T20:00:00Z") },
  { id: 212, code: "SR-1012", nameBn: "৭ মুখী রুদ্রাক্ষ (একক)", slug: "7-mukhi-rudraksha", categoryId: 101, price: 2100, oldPrice: null, image: "/images/p-mala.jpg", images: ["/images/p-mala.jpg"], shortDesc: "নেপালি ৭ মুখী অরিজিনাল রুদ্রাক্ষ", description: "নেপালের পাহাড়ি অঞ্চল থেকে সংগৃহীত ৭ মুখী রুদ্রাক্ষ।", stock: 7, soldCount: 19, isLive: true, isOffer: false, offerLabel: null, sortOrder: 12, createdAt: new Date("2026-10-01T21:00:00Z") },
];

export const FALLBACK_REVIEWS = [
  { id: 301, name: "মোঃ রবিউল ইসলাম", role: "ঢাকা", rating: 5, text: "খুব ভালো মালা পেয়েছি। দাম অনুযায়ী অসাধারণ।", avatar: null, sortOrder: 1, isActive: true },
  { id: 302, name: "লাকফোর আক্তার", role: "চট্টগ্রাম", rating: 4, text: "কাস্টমার সার্ভিস চমৎকার। দ্রুত ডেলিভারি পেয়েছি।", avatar: null, sortOrder: 2, isActive: true },
  { id: 303, name: "সুমন সাহা", role: "সিরাজগঞ্জ", rating: 5, text: "পণ্য পেয়ে খুশি হলাম। প্যাকেজিং সুন্দর ছিল।", avatar: null, sortOrder: 3, isActive: true },
];
