export type SettingsMap = Record<string, string>;

export const DEFAULT_SETTINGS: SettingsMap = {
  store_name: "সর্বতীর্থেশ্বর মহাদেব",
  store_name_2: "রুদ্রাক্ষ ভান্ডার",
  store_tagline: "Rudraksha & Puja Items | Siroganj",
  logo_image: "",
  banner_image_1: "",
  banner_image_2: "",
  banner_image_3: "",
  top_strip:
    "✦ শ্রী শ্রী সর্বতীর্থেশ্বর মহাদেবের আর্শিবাদায় বিক্রয় কেন্দ্র ✦   ·   ১০০% অরিজিনাল রুদ্রাক্ষ   ·   বিশ্বস্ত সংস্থা   ·   আপনার বিশ্বাস, আমাদের সাথী",
  phone: "01794-608874",
  phone_2: "01794-608874",
  whatsapp: "8801794608874",
  email: "sarbarthosiddhi@gmail.com",
  address: "পীরগাছা, শিবগঞ্জ, সিরাজগঞ্জ, বাংলাদেশ",
  hero_title: "সর্বতীর্থেশ্বর মহাদেব",
  hero_title_2: "রুদ্রাক্ষ ভান্ডার",
  hero_subtitle: "প্রকৃতির শক্তি, ভক্তির সাথে",
  hero_badge: "অরিজিনাল রুদ্রাক্ষ   |   পূজা সামগ্রী   |   তান্ত্রিক সামগ্রী",
  offer_title: "বিশেষ অফার চলছে",
  offer_subtitle: "সীমিত সময়ের জন্য নির্বাচিত পণ্যে বিশেষ ছাড়",
  offer_end: "",
  about_title: "আমাদের সম্পর্কে",
  about_text:
    "সর্বতীর্থেশ্বর মহাদেব রুদ্রাক্ষ ভান্ডার একটি বিশ্বস্ত ও জনপ্রিয় কেন্দ্র। আমরা সরাসরি নেপাল ও ভারত থেকে সংগ্রহ করে বিভিন্ন মুখী রুদ্রাক্ষ, পূজা সামগ্রী ও অধ্যাত্মিক উপকরণের বিক্রয় করে থাকি। আমাদের লক্ষ্য — প্রতিটি ভক্তের ঘরে পৌঁছে দেওয়া প্রকৃত ও পরিষ্কার মালামাল।",
  about_image: "/images/about-temple.jpg",
  delivery_note: "সারা বাংলাদেশে হোম ডেলিভারি · ক্যাশ অন ডেলিভারি",
  delivery_fee: "120",
  free_delivery_min: "5000",
  footer_note: "© ২০২৬ সর্বতীর্থেশ্বর মহাদেব রুদ্রাক্ষ ভান্ডার। সর্বস্বত্ব সংরক্ষিত।",
  terms_title: "শর্তাবলি",
  terms_text:
    "এই ওয়েবসাইটের মাধ্যমে অর্ডার করলে গ্রাহক পণ্যের নাম, মূল্য, ডেলিভারি চার্জ ও ডেলিভারি সময় সম্পর্কে অবগত আছেন বলে গণ্য হবে। পণ্যের কোনো দৃশ্যমান সমস্যা থাকলে ডেলিভারির ২৪ ঘণ্টার মধ্যে যোগাযোগ করতে হবে। ধর্মীয় সামগ্রী ব্যবহারের ফল ব্যক্তি ভেদে ভিন্ন হতে পারে; আমরা শুধুমাত্র পণ্যের সত্যতা ও সরবরাহের দায় বহন করি।",
  privacy_title: "গোপনীয়তা নীতি",
  privacy_text:
    "অর্ডার সম্পন্ন করা, ডেলিভারি পৌঁছে দেওয়া এবং গ্রাহক সাপোর্ট দেওয়ার জন্য আমরা গ্রাহকের নাম, মোবাইল নম্বর, ঠিকানা ও অর্ডার তথ্য সংরক্ষণ করি। এই তথ্য তৃতীয় পক্ষের কাছে বিক্রি করা হয় না। কেবল ডেলিভারি পার্টনার, পেমেন্ট ও যোগাযোগ প্রক্রিয়ার প্রয়োজনীয় সীমার মধ্যে ব্যবহার করা হয়।",
  facebook: "https://facebook.com",
  youtube: "https://youtube.com",
  theme_accent: "#d4a03c",
};

export const SETTINGS_FIELDS: { key: string; label: string; type?: "text" | "textarea" | "image"; group: string }[] = [
  { key: "banner_image_1", label: "ব্যানার ১ (রুদ্রাক্ষ) — পোস্টার ছবি, অনুপাত 925×340। খালি রাখলে ডিজাইন করা পোস্টার দেখাবে", type: "image", group: "ব্যানার পোস্টার" },
  { key: "banner_image_2", label: "ব্যানার ২ (পূজা সামগ্রী) — পোস্টার ছবি", type: "image", group: "ব্যানার পোস্টার" },
  { key: "banner_image_3", label: "ব্যানার ৩ (বিশেষ অফার) — পোস্টার ছবি", type: "image", group: "ব্যানার পোস্টার" },
  { key: "store_name", label: "দোকানের নাম (১ম লাইন)", group: "ব্র্যান্ডিং" },
  { key: "store_name_2", label: "দোকানের নাম (২য় লাইন)", group: "ব্র্যান্ডিং" },
  { key: "store_tagline", label: "ট্যাগলাইন", group: "ব্র্যান্ডিং" },
  { key: "logo_image", label: "লোগো ইমেজ URL (খালি রাখলে ডিফল্ট লোগো)", group: "ব্র্যান্ডিং" },
  { key: "top_strip", label: "উপরের ঘোষণা বার", type: "textarea", group: "ব্র্যান্ডিং" },
  { key: "hero_title", label: "হিরো শিরোনাম (১ম লাইন)", group: "হোম পেজ" },
  { key: "hero_title_2", label: "হিরো শিরোনাম (২য় লাইন)", group: "হোম পেজ" },
  { key: "hero_subtitle", label: "হিরো সাবটাইটেল", group: "হোম পেজ" },
  { key: "hero_badge", label: "হিরো ব্যাজ", group: "হোম পেজ" },
  { key: "offer_title", label: "অফার শিরোনাম", group: "অফার" },
  { key: "offer_subtitle", label: "অফার বিবরণ", type: "textarea", group: "অফার" },
  { key: "offer_end", label: "অফার শেষ হওয়ার সময় (YYYY-MM-DDTHH:MM)", group: "অফার" },
  { key: "about_title", label: "পরিচিতি শিরোনাম", group: "পরিচিতি" },
  { key: "about_text", label: "পরিচিতি লেখা", type: "textarea", group: "পরিচিতি" },
  { key: "about_image", label: "পরিচিতি ছবির URL", group: "পরিচিতি" },
  { key: "phone", label: "ফোন নম্বর ১", group: "যোগাযোগ" },
  { key: "phone_2", label: "ফোন নম্বর ২", group: "যোগাযোগ" },
  { key: "whatsapp", label: "WhatsApp নম্বর (দেশ কোডসহ, যেমন 8801794608874)", group: "যোগাযোগ" },
  { key: "email", label: "ইমেইল", group: "যোগাযোগ" },
  { key: "address", label: "ঠিকানা", type: "textarea", group: "যোগাযোগ" },
  { key: "facebook", label: "ফেসবুক লিংক", group: "সোশ্যাল" },
  { key: "youtube", label: "ইউটিউব লিংক", group: "সোশ্যাল" },
  { key: "delivery_fee", label: "ডেলিভারি চার্জ (৳)", group: "ডেলিভারি" },
  { key: "free_delivery_min", label: "ফ্রি ডেলিভারির ন্যূনতম অর্ডার (৳)", group: "ডেলিভারি" },
  { key: "delivery_note", label: "ডেলিভারি নোট", group: "ডেলিভারি" },
  { key: "footer_note", label: "ফুটার কপিরাইট", group: "সোশ্যাল" },
  { key: "terms_title", label: "শর্তাবলি শিরোনাম", group: "সোশ্যাল" },
  { key: "terms_text", label: "শর্তাবলি লেখা", type: "textarea", group: "সোশ্যাল" },
  { key: "privacy_title", label: "গোপনীয়তা নীতির শিরোনাম", group: "সোশ্যাল" },
  { key: "privacy_text", label: "গোপনীয়তা নীতির লেখা", type: "textarea", group: "সোশ্যাল" },
];

export const ORDER_STATUS: Record<string, { label: string; tone: string }> = {
  pending: { label: "অপেক্ষমাণ", tone: "bg-gold-soft text-gold-deep border-gold/40" },
  confirmed: { label: "কনফার্মড", tone: "bg-blue-50 text-navy-soft border-navy-soft/30" },
  processing: { label: "প্যাকেজিং চলছে", tone: "bg-blue-50 text-navy-soft border-navy-soft/30" },
  shipped: { label: "পাঠানো হয়েছে", tone: "bg-navy-mid text-white border-navy-mid" },
  delivered: { label: "ডেলিভারি সম্পন্ন", tone: "bg-wa/15 text-wa-deep border-wa/40" },
  cancelled: { label: "বাতিল", tone: "bg-alert/10 text-alert border-alert/30" },
};

export const ORDER_STATUS_KEYS = Object.keys(ORDER_STATUS);
